# Generated by Django 5.2.4 on 2025-07-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="fitness_class",
            new_name="class_id",
        ),
    ]
